### ISSUE TITLE
Tracking Issue before deadline

### ISSUE THREAD

**Issue by cmwaters** [marbar3778/Entropy#33]
List of things we want to tick off before the deadline:

- [ ] Be able to deposit funds to a lending reserve via the front end
- [ ] Add instructions to front end to execute `open` and `close` positions 
- [ ] Add modified lending contract and margin contract to devnet (and update the FE with the respective program id's)
- [ ] Setup accounts, currencies and reserves and do a filmed run of the user flow on the devnet (or do we plan to do this live)

Feel free to add other stuff that you think belongs on this list
